[project]
name = "adventofcode-2025"
version = "0.1.0"
description = "Python project for solving Advent of Code 2025 problems"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "igraph>=1.0.0",
    "matplotlib>=3.10.7",
    "shapely>=2.1.2",
    "z3>=0.2.0",
]
